# Ch. 2 Linear Algebra

## 2.1 Scalars, Vectors, Matrices and Tensors  
* **Scalar**: Single number  
* **Vector**: Array of numbers
* **Matrix**: 2-D array of numbers  
* **Tensor**: Array of numbers on a regular grid with a variable number of axis

### Transpose
${\displaystyle \left( A ^{\operatorname {T}}\right)_{ij}=\left(A \right)_{ji}.}$

In [66]:
import torch
A = torch.randn(2, 3)
A

tensor([[-0.7294,  1.3618, -0.4404],
        [ 2.7210,  0.5533,  0.2834]])

In [67]:
A.shape

torch.Size([2, 3])

In [68]:
torch.transpose(A, 0, 1)

tensor([[-0.7294,  2.7210],
        [ 1.3618,  0.5533],
        [-0.4404,  0.2834]])

In [69]:
torch.transpose(A, 0, 1).shape

torch.Size([3, 2])

## 2.2 Multiplying Matrices and Vectors
${\displaystyle C = A B}.$  
${\displaystyle C_{i,j} = \sum _{k}A_{i,k}B_{k,j}.}$  
Not to be confused with element-wise product, or Hadamard product (${\displaystyle A \odot B}$). 

In [70]:
B = torch.randn(3, 2)
B

tensor([[ 0.1433, -1.0222],
        [-1.4730,  0.8913],
        [ 1.5465, -0.1831]])

In [71]:
B.shape

torch.Size([3, 2])

In [72]:
A @ B

tensor([[-2.7914,  2.0400],
        [ 0.0132, -2.3403]])

In [73]:
(A @ B).shape

torch.Size([2, 2])

@ **is** distributive  
${\displaystyle A \left( B + C \right) = AB + AC}.$  

In [74]:
C = torch.randn_like(B)
C

tensor([[-0.4825,  1.5713],
        [ 1.0060,  0.5823],
        [-1.2608,  1.2654]])

In [75]:
C.shape

torch.Size([3, 2])

In [76]:
torch.all(torch.isclose(A @ (B + C), A @ B + A @ C))

tensor(True)

@ **is** associative  
${\displaystyle A \left( BC \right) = \left( AB \right) C}.$  

In [77]:
D = torch.randn(2, 6)
D

tensor([[ 0.5763, -0.0558, -1.5430,  1.6122,  0.2125,  0.2867],
        [ 0.0906, -0.4179,  1.2430, -0.0191, -0.5927,  0.5629]])

In [78]:
D.shape

torch.Size([2, 6])

In [79]:
torch.all(torch.isclose(A @ (B @ D), (A @ B) @ D))

tensor(True)

@ is **not always** commutative  
${\displaystyle AB = BA}.$ 

In [80]:
(A @ B).shape

torch.Size([2, 2])

In [81]:
(B @ A).shape

torch.Size([3, 3])

Transpose of matrix product  
${\displaystyle \left( AB \right) ^{\operatorname {T}} = B ^{\operatorname {T}} A ^{\operatorname {T}}}.$

In [82]:
torch.all(torch.isclose((A @ B).transpose(0, 1), B.transpose(0, 1) @ A.transpose(0, 1)))

tensor(True)

System of linear equations  
${\displaystyle A x = b}$  
${\displaystyle \\ \text {where} \: A \in \mathbb {R} ^ {m \times n}, \: b \in \mathbb {R} ^ {m}, \:  \text{and} \: x \in \mathbb{R} ^ {n}.}$

In [83]:
m, n = 4, 5
A = torch.randn(m, n)
x = torch.randn(n)
b = torch.randn(m)

In [84]:
(A @ x).shape

torch.Size([4])

In [85]:
b.shape

torch.Size([4])

## 2.3 Identity and Inverse Matrices  
* **Identity Matrix**: a matrix that does not change any vector when we multiply that vector by that matrix.  
${\displaystyle I_{n} \in \mathbb {R} ^{n \times n}}$, and  
${\displaystyle \forall x \in \mathbb {R} ^{n}, \: I_{n}x = x.}$  
${\displaystyle \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}}$  
* The **matrix inverse** of **A** is denoted as ${\displaystyle A ^{-1}}$, and is defined as the matrix such that  
${\displaystyle A ^{-1} A = I_{n}.}$  
* The system of linear equations above can now be solved using the following steps:  
${\displaystyle A x = b}$  
${\displaystyle A ^{-1} A x = A ^{-1} b}$  
${\displaystyle I_{n} x = A^{-1} b.}$
* ${\displaystyle A^{-1}}$ is not always possible to find and is primarily useful as a theoretical tool.  